### ISSUE TITLE
Use Node 20 instead of Node 16

### ISSUE THREAD

**Issue by tim-we** [kielabokkie/ssh-key-and-known-hosts-action#29]
This action still uses Node 16: https://github.com/kielabokkie/ssh-key-and-known-hosts-action/blob/fd3b0d6032f9b6221aa4e58f975be862e1a27697/action.yml#L20

This node version has reached end of life and causes a warning message in workflows using it:
![image](https://github.com/kielabokkie/ssh-key-and-known-hosts-action/assets/10491533/5386407f-d52a-41b1-a3d3-a43d92fe6c1c)

As far as I can tell the change required should be fairly trivial.

For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/

PR to fix this: https://github.com/kielabokkie/ssh-key-and-known-hosts-action/pull/30

**Comment by HausTechTeam** [comment]
We're also interested in Node 20 support for this action. Nice work with the PR 👍

**Comment by kohlerdominik** [comment]
Ping @kielabokkie 

We would need this as well.

**Comment by kielabokkie** [comment]
Apologies for the delay. I've just released v1.4.0 which now uses Node 20, thanks @tim-we!
