### ISSUE TITLE
Getting Errorr for ssh-auth.sock process still running.

### ISSUE THREAD

**Issue by kandji-leon** [kielabokkie/ssh-key-and-known-hosts-action#3]
Worked when I ran it the first time, but the second time got this error. Had to manually kill the process on the runner. Using self hosted runner no docker.
```
Run kielabokkie/ssh-key-and-known-hosts-action@v1
Starting ssh-agent
Error: Command failed with exit code 1: ssh-agent -a /tmp/ssh-auth.sock
bind: Address already in use
unix_listener: cannot bind to path: /tmp/ssh-auth.sock
```

**Comment by kielabokkie** [comment]
@kandji-leon Thanks for reporting this issue. I don't use self-hosted runners so can't replicate the issue. You might be able to use an if conditional in your workflow to check if the ssh-agent is already running as it persists between runs.

Please let me know if you end up with something that works so I can add it to the readme as a note.
