### ISSUE TITLE
Error due to ::set-env getting deprecated

### ISSUE THREAD

**Issue by lynxlynxlynx** [kielabokkie/ssh-key-and-known-hosts-action#4]
Hey, started getting errors with the action:
> Run kielabokkie/ssh-key-and-known-hosts-action@v1
>   with:
>     ssh-private-key: ***
>     ssh-host: frs.sourceforge.net
> Starting ssh-agent
> Error: The `set-env` command is deprecated and will be disabled on November 16th. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

From a quick glance It appears the last commit fixed it upstream, so I guess you need to regenerate dist.js, as it's the only remaining mention.

**Comment by kielabokkie** [comment]
Thanks for reporting this @lynxlynxlynx. I've tagged a new version that should fix this issue.

**Comment by lynxlynxlynx** [comment]
Verified, thanks!
